name: Owl Book CI Workflow

on:
  push:
    branches:
      - master123
  pull_request:
    branches:
      - master123

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: owlbarn/book:latest

    steps:
      - name: Checkout the book
        uses: actions/checkout@v2
        with:
          path: book-workflow

      - name: Compile the book
        working-directory: ./book-workflow
        run: |
          chown -R opam . &&
          su - opam -c 'export PATH=/home/opam/.cabal/bin:${PATH} && cd /__w/book/book/book-workflow && make compile'
          cd /__w/book/book/book-workflow
          date >> HISTORY.log

      - name: Save to the repository
        working-directory: ./book-workflow
        if: ${{ always() }}
        run: |
          git config user.name "owlbook_ci"
          git config user.email "ryanrhymes@gmail.com"
          git commit -am "[owlbook_ci] automated book compilation"
          git push

#      - name: Checkout the website
#        uses: actions/checkout@v2
#        with:
#          repository: owlbarn/owlbarn.github.io
#          path: owlbarn.github.io
#          token: ${{ secrets.OWLBOOK_CI_TOKEN }}
#
#      - name: Update the website
#        working-directory: owlbarn.github.io
#        if: ${{ always() }}
#        env:
#          API_TOKEN_GITHUB: ${{ secrets.OWLBOOK_CI_TOKEN }}
#        run: |
#          git config user.name "owlbook_ci"
#          git config user.email "ryanrhymes@gmail.com"
#          git commit -am "[owlbook_ci] automated book and website update"
#          git push https://ryanrhymes:${API_TOKEN_GITHUB}@github.com/owlbarn/owlbarn.github.io/
